### PR TITLE
Implement new SMTP SSL env variable and upgrade base image

### PR DESCRIPTION
**Pull request by lord-kyron**
Hi,
I've made some changes to implement the latest SMTP options to the helm chart + bump the image to the latest version, as I've explained here:
https://github.com/gissilabs/charts/issues/35

@sgissi - please, review the changes!
Thanks!

### CODE REVIEW

**Comment by lord-kyron** [comment]
@sgissi can you please, check and merge this if it is ok?
It will help using the implementations for the newest version of Vaultwarden image.

**Comment by sgissi** [comment]
Hi @lord-kyron, thanks a lot for the PR! That would break backwards compatibility, I would prefer to deprecate the settings: add a warning at NOTES.txt, a notice at README and prefer smtp.security over smtp.ssl/explicittls. But I wouldn't like to break existing installations of the chart, particularly when while upstream still supports the old env variables.

Do you know the first version of Vaultwarden that supports SSL_SECURITY?

**Comment by lord-kyron** [comment]
Hi @sgissi,
Yes here is the official statement:
```
From v1.25.0, environment variable for SMTP SSL/TLS configuration has been updated to SMTP_SECURITY (which was mislabelled, see bug #851).

```

**Comment by sgissi** [comment]
Thank you for the update. It looks like the option was deprecated fully upstream (https://github.com/dani-garcia/vaultwarden/commit/42136a70973f60086749c62439c6a965d4589c02) so upgrading will be a breaking change in any case. My recommendation for this PR is:
- Do not bump the chart version yet, I'll do it separately with some other changes. It will become 1.0.0 as it breaks backward compatibility
- Use the latest application patch (1.25.1)
- In deployment.yaml, detect usage of ssl/explicittls on image tag is >= 1.25.0 (semverCompare might be handy here) and throw an error out that these variables aren't supported in that version. That will catch people upgrading without changing the setting.
- Remove smtp.ssl and smtp.explicitTLS
- Add a deprecation node to the top of README, probably a good time to stop updates to bitwardenrs helm chart too.

**Comment by lord-kyron** [comment]
@sgissi - can you please, take a look what I've done to the pull request, according to your recommendations (please, check the deployments.yaml template as I am not sure about the 'if semVer' statements and syntax/indent are right).
Thanks!

**Comment by jonkerj** [comment]
Any news? I'm using this chart, and not having this PR prevents me from updating Vaultwarden

**Comment by lord-kyron** [comment]
@sgissi please

**Comment by sgissi** [comment]
Thanks for the updates, life got really busy lately :) I'll review them this weekend. In the meantime, you can use the "extraEnv" to supply the right values to Vaultwarden until the chart catches up.

**Comment by jonkerj** [comment]
Any chance you can look at it?

**Comment by lord-kyron** [comment]
@sgissi it will be great if you can check what I improved and merge it!

**Comment by benedikt-bartscher** [comment]
@sgissi, new year, new luck? :)

**Comment by lord-kyron** [comment]
@sgissi Happy New year :) Can you please check my latest changes to this pull request? We really need the changes for this alraedy.

**Comment by sgissi** [comment]
Hi @lord-kyron, @benedikt-bartscher and @jonkerj. Thanks again for the PR updates and sorry for the delayed review. I'll merge these to a branch and work out some more updates to Vaultwarden 1.27 before merging to master and releasing new charts.

**Comment by lord-kyron** [comment]
Thank you @sgissi !

**Pull request merged**
