### PR TITLE
Vaultwarden: Add option to specify key for existing database secret

### PR DESCRIPTION
**Pull request by DerDaku**
I added an option to specify a secret key other than 'database-url' for the database secret.

### CODE REVIEW

**Comment by sgissi** [comment]
Hi @DerDaku, that looks good! I'll run some quick tests and merge/release on the weekend. Thank you for contributing!

**Comment by aschaber1** [comment]
Hello @sgissi , any update? A merge & release would be appreciated.

**Comment by sgissi** [comment]
Sorry for the delay, it has been quite busy :( It is a long weekend, I'll try to release it by Monday.

**Comment by aschaber1** [comment]
friendly ping :)

**Comment by sgissi** [comment]
Thanks @aschaber1! Sorry it took incredibly long, I'm catching up now.

**Pull request merged**
