### PR TITLE
Extra Env variables and Traefik middleware

### LINKED ISSUE #4: [Feature] [Bitwarden] Custom env vars option
For future proofing it might be interesting to at least add the option to include additional custom env-vars that are not pre-defined into the values.yaml file.

A bit of what this version of helm-for-bitwarden_rs does, but while keeping your amazing list of config options:
https://github.com/cdwv/bitwarden-k8s

### PR DESCRIPTION
**Pull request by sgissi**
Allow option to inject environment variables manually.
Add option to select middlewares for Traefik IngressRoute.

@Ornias1993 Can you test please? I have based this out of your patches but fixed the middleware. They are placed at "route" level instead of top-level like TLS or entrypoints.

Replaces #7, fixes #4 and #5.

### CODE REVIEW

**Comment by Ornias1993** [comment]
You couldve just commited to my branch instead >.<

**Comment by sgissi** [comment]
Sorry, I didn't realize that was possible, let me try that.

**Comment by Ornias1993** [comment]
No problem, i'm also fine with merging this into mine.

That being said:

> I have based this out of your patches but fixed the middleware. They are placed at "route" level instead of top-level like TLS or entrypoints.

Please don't use a different structure than the CRD itself. So keep it in the same place for people that are used to working with the CRD directly.

**Comment by sgissi** [comment]
> > I have based this out of your patches but fixed the middleware. They are placed at "route" level instead of top-level like TLS or entrypoints.
> 
> Please don't use a different structure than the CRD itself. So keep it in the same place for people that are used to working with the CRD directly.
Absolutely. I misread your changes actually, I thought they were at a higher level but you did place them correctly under the routes. It was missing the same middlewares injected in the websocket part. I don't run any middleware, can you test on the new branch? I'll close this PR for now.

**Comment by Ornias1993** [comment]
Yeah I missed one route, sorry! >.<

**Comment by Ornias1993** [comment]
Fine with closing btw! :)

**Pull request closed without merging**
